version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "localpassword"
      POSTGRES_DB: "user-api"
    volumes:
      - ./_data:/var/lib/postgresql/data